-- Create a table for storing user profiles
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  updated_at timestamp with time zone,
  username text unique,
  full_name text,
  avatar_url text,
  website text,

  constraint username_length check (char_length(username) >= 3)
);

-- Set up Row Level Security (RLS)
alter table public.profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on public.profiles for select
  using (true);

create policy "Users can insert their own profile."
  on public.profiles for insert
  with check (auth.uid() = id);

create policy "Users can update own profile."
  on public.profiles for update
  using (auth.uid() = id);

-- Create a trigger to insert a new profile when a user is created
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Create a table for storing OTP tokens (optional, if you want to store OTP attempts)
create table if not exists public.otp_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade,
  email text,
  token text,
  expires_at timestamp with time zone not null,
  created_at timestamp with time zone default now()
);

-- Set up RLS for OTP attempts
alter table public.otp_attempts enable row level security;

create policy "Users can view their own OTP attempts."
  on public.otp_attempts for select
  using (auth.uid() = user_id);

create policy "Users can insert their own OTP attempts."
  on public.otp_attempts for insert
  with check (auth.uid() = user_id);